# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 02:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal_external_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalexternalcomment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_internalexternalcomment', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='internalexternalcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internalexternalcomment_comments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
