# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal_external_comments', '0002_auto_20171103_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalexternalcomment',
            options={'permissions': (('can_post_internal', 'Can post internal message'), ('can_delete_internal', 'Can delete internal message'), ('can_edit_internal', 'Can edit internal message'), ('can_view_internal', 'Can view internal message'), ('can_delete_external', 'Can delete external message'), ('can_edit_external', 'Can edit external message')), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
